# tells app engine to run code inside Python 3.8 sandbox
runtime: Python38
# tells app engine to run version 8 of the API
api-version: 8
# code is threadsafe, app engine can run without worrying about threads
threadsafe: true

# holds handlers that map URL patters to a given script
handlers:
  # regex that's matched against requests
  -url: /.*
  # points to main.py file, .app tells the app engine to treat
  # main.py as a web server gateway interface application
  # aka tells it to look at the app variable in main.py
  script: main.app 