runtime: python38
entrypoint: gunicorn -b 0.0.0.0:8080 main:server

## required, currently using python39
#runtime: python39
## selecting the environment
## gunicorn is a WSGI server implementation commonly used to run Python web apps
## -b (bind) is used to specify a server socket to bind
## $(HOST) server socket
## main:app - file we want it to run
#entrypoint: gunicorn -b :$PORT main:app
#
#handlers:
#  - url: /.*
#    script: main.app